// AI Card Battle — card registry + decklists (Phase-0, all four factions).
// Balance-review fixes applied (see docs/CARDS.md). Handlers mutate ONLY via
// ctx.api (which resolves deaths / On Sunset / win checks).
// Some twists are simplified for the prototype and flagged with [sim].

function bestFriendly(api) { const b = api.myBoard(); return b.length ? b.reduce((a, m) => (m.attack >= a.attack ? m : a)) : null; }

export const CARDS = {
  // ---- tokens / shared ----
  open_weights: { id: "open_weights", name: "Open Weights", cost: 0, type: "Op", keywords: [], rarity: "Common",
    text: "Gain +1 temporary Compute this turn.", op: (S, c) => c.api.addTempCompute(1) },
  token_11: { id: "token_11", name: "Token", cost: 0, type: "Model", attack: 1, health: 1, keywords: ["Ship It"], rarity: "Common", text: "Ship It." },
  gemma_token: { id: "gemma_token", name: "Gemma (Open)", cost: 0, type: "Model", attack: 4, health: 4, keywords: [], rarity: "Common", text: "Open Source copy." },
  whale_token: { id: "whale_token", name: "Whale (Open)", cost: 0, type: "Model", attack: 4, health: 5, keywords: [], rarity: "Common", text: "Open Source copy." },

  // ================= ClosedAI — Aggro / Hype =================
  demo_day_intern: { id: "demo_day_intern", name: "Demo-Day Intern", cost: 1, type: "Model", attack: 2, health: 1, keywords: ["Ship It"], rarity: "Common",
    text: "Ship It. On Deploy: +Hype 1 if you control another Model.",
    onDeploy: (S, c) => { if (c.api.myBoard().length > 1) c.api.giveHype(c.self, 1); } },
  vaporware_teaser: { id: "vaporware_teaser", name: "Vaporware Teaser", cost: 1, type: "Op", keywords: ["Hype"], announce: true, requiresTarget: true, targetKind: "friendlyModel", rarity: "Common",
    text: "Give a friendly Model Hype 2 (Hype 3 if 6+ Compute spent this game).",
    op: (S, c) => { const m = c.api.findModel(c.targetId); if (m) c.api.giveHype(m, c.api.scaling() >= 6 ? 3 : 2); } },
  hype4_omni: { id: "hype4_omni", name: "Hype-4 Omni", cost: 2, type: "Model", attack: 3, health: 2, keywords: ["On Deploy"], rarity: "Common",
    text: "On Deploy: deal 1 to the enemy CEO, then +Hype 1.",
    onDeploy: (S, c) => { c.api.dealDamage("HERO_" + c.api.opp, 1); c.api.giveHype(c.self, 1); } },
  closed_beta_brigade: { id: "closed_beta_brigade", name: "Closed Beta Brigade", cost: 2, type: "Model", attack: 3, health: 2, keywords: ["Ship It", "Stealth Mode"], rarity: "Rare",
    text: "Ship It, Stealth Mode. When it hits the enemy CEO, deal 1 more.",
    onCombatHeroDamage: (S, c) => c.api.dealDamage("HERO_" + c.api.opp, 1) },
  move_fast_break_prod: { id: "move_fast_break_prod", name: "Move Fast, Break Prod", cost: 3, type: "Op", keywords: [], requiresTarget: true, targetKind: "any", rarity: "Rare",
    text: "Deal 3 to a target. If it hits the enemy CEO, give a friendly Model Hype 3.",
    op: (S, c) => { c.api.dealDamage(c.targetId, 3); if (c.targetId === "HERO_" + c.api.opp) { const m = bestFriendly(c.api); if (m) c.api.giveHype(m, 3); } } },
  series_f_frenzy: { id: "series_f_frenzy", name: "Series-F Frenzy", cost: 3, type: "Model", attack: 3, health: 3, keywords: ["On Deploy"], rarity: "Rare",
    text: "On Deploy: give all other friendly Models Hype 1.",
    onDeploy: (S, c) => { for (const m of c.api.myBoard()) if (m.iid !== c.self.iid) c.api.giveHype(m, 1); } },
  surprise_keynote: { id: "surprise_keynote", name: "Surprise Keynote", cost: 4, type: "Model", attack: 4, health: 3, keywords: ["Launch Day"], rarity: "Epic", text: "Launch Day." },
  pivot_to_hardware: { id: "pivot_to_hardware", name: "Pivot to Hardware", cost: 3, type: "Hardware", keywords: [], rarity: "Epic",
    text: "Equip a 3-Attack Launch (2 charges). On Deploy: give a friendly Model Hype 1.",
    onDeploy: (S, c) => { c.api.equipLaunch(3, 2); const m = bestFriendly(c.api); if (m) c.api.giveHype(m, 1); } },
  founder_mode_sam: { id: "founder_mode_sam", name: "Founder Mode Sam", cost: 5, type: "Legendary Model", attack: 4, health: 4, keywords: ["On Deploy", "Launch Day"], rarity: "Legendary",
    text: "On Deploy: X = Announce casts (max 3). Give every friendly Model Hype X and deal X to the enemy CEO.",
    onDeploy: (S, c) => { const x = Math.min(3, c.me.announce); for (const m of c.api.myBoard()) c.api.giveHype(m, x); if (x > 0) c.api.dealDamage("HERO_" + c.api.opp, x); } },
  total_addressable_market: { id: "total_addressable_market", name: "Total Addressable Market", cost: 6, type: "Op", keywords: [], rarity: "Legendary",
    text: "Deal damage to the enemy CEO equal to your total board Attack (max 8).",
    op: (S, c) => { const total = c.api.myBoard().reduce((s, m) => s + m.attack, 0); c.api.dealDamage("HERO_" + c.api.opp, Math.min(8, total)); } },

  // ================= Anthrabbit — Control / Safety =================
  paperclip_auditor: { id: "paperclip_auditor", name: "Paperclip Auditor", cost: 1, type: "Model", attack: 1, health: 3, keywords: ["Guardrail"], rarity: "Common", text: "Guardrail." },
  red_team_rabbit: { id: "red_team_rabbit", name: "Red-Team Rabbit", cost: 2, type: "Model", attack: 2, health: 2, keywords: ["On Deploy"], rarity: "Common",
    text: "On Deploy: gain 2 Safety Margin.", onDeploy: (S, c) => c.api.gainArmor(2) },
  constitutional_clause: { id: "constitutional_clause", name: "Constitutional Clause", cost: 2, type: "Op", keywords: [], requiresTarget: true, targetKind: "enemyModel", rarity: "Common",
    text: "Deal 3 to a Model. If its Attack >= 4, gain 3 Safety Margin.",
    op: (S, c) => { const m = c.api.findModel(c.targetId); const big = m && m.attack >= 4; c.api.dealDamage(c.targetId, 3); if (big) c.api.gainArmor(3); } },
  alignment_researcher: { id: "alignment_researcher", name: "Alignment Researcher", cost: 3, type: "Model", attack: 2, health: 4, keywords: ["Guardrail", "On Deploy"], rarity: "Rare",
    text: "Guardrail. On Deploy: restore 3 Valuation.", onDeploy: (S, c) => c.api.heal(3) },
  sandbox_containment: { id: "sandbox_containment", name: "Sandbox Containment", cost: 3, type: "Op", keywords: [], requiresTarget: true, targetKind: "enemyModel", rarity: "Rare",
    text: "An enemy Model can't attack / use Guardrail until your next turn. Draw a card.",
    op: (S, c) => { const m = c.api.findModel(c.targetId); if (m) c.api.contain(m); c.api.draw(1); } },
  failover_cluster: { id: "failover_cluster", name: "Failover Cluster", cost: 4, type: "Model", attack: 3, health: 4, keywords: ["Guardrail", "Failover"], rarity: "Rare", text: "Guardrail, Failover." },
  rapid_rollback: { id: "rapid_rollback", name: "Rapid Rollback", cost: 4, type: "Op", keywords: [], rarity: "Rare",
    text: "Restore 6 Valuation. If you control a Guardrail Model, gain 2 Safety Margin.",
    op: (S, c) => { c.api.heal(6); if (c.api.myBoard().some((m) => m.keywords.includes("Guardrail"))) c.api.gainArmor(2); } },
  interpretability_lattice: { id: "interpretability_lattice", name: "Interpretability Lattice", cost: 5, type: "Hardware", keywords: [], rarity: "Epic",
    text: "Ongoing (2 turns): start of your turn restore 2 Valuation; your first Op costs 1 less. [nerf: 3->2 turns]",
    onDeploy: (S, c) => { c.me.ongoingLattice = (c.me.ongoingLattice || 0) + 2; } },
  the_long_horizon_plan: { id: "the_long_horizon_plan", name: "The Long-Horizon Plan", cost: 7, type: "Op", keywords: ["Scaling Laws"], rarity: "Epic",
    text: "Deal 2 + 1 per 10 Compute spent to all enemy Models, and gain that much Safety Margin. [nerf: 6->7cc]",
    op: (S, c) => { const amt = 2 + Math.floor(c.api.scaling() / 10); c.api.damageAllEnemyModels(amt); c.api.gainArmor(amt); } },
  claudius: { id: "claudius", name: "Claudius the Considerate", cost: 8, type: "Legendary Model", attack: 6, health: 8, keywords: ["Guardrail", "Monetize", "On Deploy"], rarity: "Legendary",
    text: "Guardrail, Monetize. On Deploy: restore Valuation = your Safety Margin (max 8). Realign costs 1 less while in play.",
    onDeploy: (S, c) => { c.api.heal(Math.min(8, c.me.armor)); c.me.hero.powerDiscount = 1; },
    onSunset: (S, c) => { c.me.hero.powerDiscount = 0; } },

  // ================= Googlitch — Ramp / Big-Compute Value =================
  pod_provisioner: { id: "pod_provisioner", name: "Pod Provisioner", cost: 1, type: "Model", attack: 0, health: 4, keywords: ["Guardrail"], rarity: "Common",
    text: "Guardrail. On Sunset: gain +1 max Compute. [buff: 0/4]", onSunset: (S, c) => c.api.addCompute(1) },
  spin_up_tpu: { id: "spin_up_tpu", name: "Spin Up a TPU Pod", cost: 1, type: "Op", keywords: [], rarity: "Common",
    text: "Gain +1 max Compute (cap 8), refill 1 Compute, and draw a card. [buff: +draw]", op: (S, c) => { c.api.addCompute(1); c.api.refillCompute(1); c.api.draw(1); } },
  index_crawler: { id: "index_crawler", name: "Index Crawler", cost: 2, type: "Model", attack: 1, health: 4, keywords: ["Guardrail", "On Deploy"], rarity: "Common",
    text: "Guardrail. On Deploy: draw a card. [sim: scry]", onDeploy: (S, c) => c.api.draw(1) },
  search_index: { id: "search_index", name: "Search & Index", cost: 3, type: "Op", keywords: [], rarity: "Common",
    text: "Draw 2. If you have 6+ max Compute, draw 3 instead.", op: (S, c) => c.api.draw(c.me.compute.max >= 6 ? 3 : 2) },
  glitch_in_stack: { id: "glitch_in_stack", name: "Glitch in the Stack", cost: 3, type: "Op", keywords: ["Scaling Laws"], requiresTarget: true, targetKind: "enemyChar", rarity: "Rare",
    text: "Deal 2 + 1 per 12 Compute spent to any enemy target. [buff: reach — can hit the CEO]", op: (S, c) => c.api.dealDamage(c.targetId, 2 + Math.floor(c.api.scaling() / 12)) },
  bardo_hallucinator: { id: "bardo_hallucinator", name: "Bardo the Hallucinator", cost: 4, type: "Model", attack: 3, health: 5, keywords: ["Overclock", "Glitch"], rarity: "Rare",
    text: "Overclock. Glitch: deal 1 to a friendly Model.",
    onGlitch: (S, c) => { const b = c.api.myBoard().filter((m) => m.iid !== c.self.iid); if (b.length) c.api.dealDamage(b[0].iid, 1); } },
  tpu_megapod: { id: "tpu_megapod", name: "TPU Megapod", cost: 4, type: "Hardware", keywords: [], rarity: "Epic",
    text: "On equip: gain +2 max Compute (cap 8). [sim: scry/charges omitted]", onDeploy: (S, c) => c.api.addCompute(2) },
  sunset_protocol: { id: "sunset_protocol", name: "Sunset Protocol", cost: 4, type: "Op", keywords: [], rarity: "Epic",
    text: "Deal 3 to ALL Models. Draw a card for each enemy Model destroyed.",
    op: (S, c) => { const before = c.api.enemyBoard().length; c.api.damageAllModels(3); const killed = before - c.api.enemyBoard().length; if (killed > 0) c.api.draw(killed); } },
  gemma_twins: { id: "gemma_twins", name: "Gemma Twins, the Open Release", cost: 5, type: "Model", attack: 4, health: 4, keywords: ["On Deploy"], rarity: "Epic",
    text: "On Deploy: summon a 4/4 copy into the shared Open Source zone.",
    onDeploy: (S, c) => c.api.summonShared("gemma_token", { attack: 4, health: 4 }) },
  gemini_ascendant: { id: "gemini_ascendant", name: "Gemini Ascendant, Frontier Titan", cost: 8, type: "Legendary Model", attack: 8, health: 8, keywords: ["Guardrail", "On Deploy", "Glitch"], rarity: "Legendary",
    text: "Guardrail. On Deploy: deal 3 to all enemy Models and 4 to the enemy CEO, then refill Compute to full. Glitch: lose 1 Attack. [buff: +4 face reach]",
    onDeploy: (S, c) => { c.api.damageAllEnemyModels(3); c.api.dealDamage("HERO_" + c.api.opp, 4); c.api.fullRefill(); },
    onGlitch: (S, c) => { c.self.attack = Math.max(0, c.self.attack - 1); } },

  // ================= ShallowSeek — Swarm / Efficiency Combo =================
  distil_bot_v3: { id: "distil_bot_v3", name: "Distil-Bot V3", cost: 1, type: "Model", attack: 2, health: 1, keywords: ["Ship It"], rarity: "Common",
    text: "Ship It. On Deploy: the next Model you play this turn costs 1 less.",
    onDeploy: (S, c) => { c.me.nextModelDiscount = 1; } },
  token_faucet: { id: "token_faucet", name: "Token Faucet", cost: 1, type: "Op", keywords: [], rarity: "Common",
    text: "Summon two 1/1 Ship It Tokens. If you've already played a card this turn, summon a third.",
    op: (S, c) => { const n = (c.me.cardsPlayedThisTurn || 0) >= 1 ? 3 : 2; for (let i = 0; i < n; i++) c.api.summon("token_11"); } },
  quantize: { id: "quantize", name: "Quantize", cost: 1, type: "Op", keywords: [], rarity: "Rare",
    text: "Reduce the cost of all cards in your hand by 1 this turn.", op: (S, c) => { c.me.handDiscount = (c.me.handDiscount || 0) + 1; } },
  open_weights_intern: { id: "open_weights_intern", name: "Open-Weights Intern", cost: 2, type: "Model", attack: 2, health: 3, keywords: ["On Deploy"], rarity: "Common",
    text: "On Deploy: if this is your 3rd+ card this turn, draw a card.",
    onDeploy: (S, c) => { if ((c.me.cardsPlayedThisTurn || 0) >= 2) c.api.draw(1); } },
  fork_the_repo: { id: "fork_the_repo", name: "Fork the Repo", cost: 2, type: "Op", keywords: [], requiresTarget: true, targetKind: "friendlyModelCheap", rarity: "Rare",
    text: "Summon a copy of a friendly Model that costs 2 or less (current stats, no On Deploy).",
    op: (S, c) => { const m = c.api.findModel(c.targetId); if (m) c.api.summon(m.cardId, { attack: m.attack, health: m.health }); } },
  mixture_of_interns: { id: "mixture_of_interns", name: "Mixture-of-Interns", cost: 3, type: "Model", attack: 3, health: 5, keywords: ["Guardrail", "On Deploy"], rarity: "Rare",
    text: "Guardrail. On Deploy: +1/+1 per other friendly Model (max +3/+3).",
    onDeploy: (S, c) => { const n = Math.min(3, c.api.myBoard().filter((m) => m.iid !== c.self.iid).length); if (n > 0) c.api.buff(c.self, n, n); } },
  sparse_activation: { id: "sparse_activation", name: "Sparse Activation", cost: 3, type: "Op", keywords: [], rarity: "Rare",
    text: "Give all friendly Models +2 Attack this turn and Ship It. [buff: +2]",
    op: (S, c) => { for (const m of c.api.myBoard()) { m.attack += 2; m.tempAtk = (m.tempAtk || 0) + 2; m.summoningSick = false; } } },
  whale_class_cluster: { id: "whale_class_cluster", name: "Whale-Class Cluster", cost: 4, type: "Hardware", keywords: [], rarity: "Epic",
    text: "Equip a 2-Attack Launch (3 charges). Whenever you play a Model, this Launch gains +1 charge (max 5).",
    onDeploy: (S, c) => c.api.equipLaunch(2, 3, { chargeOnModelPlay: true, maxCharges: 5 }) },
  inference_cascade: { id: "inference_cascade", name: "Inference Cascade", cost: 4, type: "Op", keywords: ["Scaling Laws"], rarity: "Epic",
    text: "Deal to the enemy CEO = your Model count + 1 per 12 Compute spent (max 10). [buff: 4cc, max 10]",
    op: (S, c) => { const n = c.api.myBoard().length + Math.floor(c.api.scaling() / 12); c.api.dealDamage("HERO_" + c.api.opp, Math.min(10, n)); } },
  the_whale_open_sourced: { id: "the_whale_open_sourced", name: "The Whale, Open-Sourced", cost: 5, type: "Legendary Model", attack: 4, health: 5, keywords: ["On Deploy", "On Sunset"], rarity: "Legendary",
    text: "On Deploy: -1 cost to your hand this turn; summon a 1/1 Token per card in hand (max 3). On Sunset: place a 4/5 copy in the shared zone.",
    onDeploy: (S, c) => { c.me.handDiscount = (c.me.handDiscount || 0) + 1; const n = Math.min(3, c.me.hand.length); for (let i = 0; i < n; i++) c.api.summon("token_11"); },
    onSunset: (S, c) => c.api.summonShared("whale_token", { attack: 4, health: 5 }) },
};

export const HERO_POWERS = {
  ClosedAI: { name: "Hype Ping", cost: 2, requiresTarget: true,
    targets: (S, seat) => { const o = seat === "A" ? "B" : "A"; return [...S.players[o].board.filter((m) => !m.stealth).map((m) => m.iid), "HERO_" + o]; },
    use: (S, c) => { const tid = c.targetId; c.api.dealDamage(tid, 1); const killed = tid.startsWith("m") && !c.api.findModel(tid); const face = tid === "HERO_" + c.api.opp; if (killed || face) { const m = bestFriendly(c.api); if (m) c.api.giveHype(m, 1); } } },
  Anthrabbit: { name: "Realign", cost: 2, requiresTarget: false,
    use: (S, c) => { if (c.me.valuation >= c.me.maxValuation) c.api.gainArmor(2); else c.api.heal(2); } },
  Googlitch: { name: "Index & Scry", cost: 2, requiresTarget: false, use: (S, c) => c.api.draw(1) },
  ShallowSeek: { name: "Spin Up", cost: 2, requiresTarget: false, use: (S, c) => c.api.addTempCompute(1) },
};

function dup(ids) { return ids.flatMap((id) => [id, id]); }

export const DECKS = {
  closedai: { company: "ClosedAI", name: "ClosedAI — Aggro/Hype",
    cards: dup(["demo_day_intern", "vaporware_teaser", "hype4_omni", "closed_beta_brigade", "move_fast_break_prod", "series_f_frenzy", "surprise_keynote", "pivot_to_hardware", "founder_mode_sam", "total_addressable_market"]) },
  anthrabbit: { company: "Anthrabbit", name: "Anthrabbit — Control/Safety",
    cards: dup(["paperclip_auditor", "red_team_rabbit", "constitutional_clause", "alignment_researcher", "sandbox_containment", "failover_cluster", "rapid_rollback", "interpretability_lattice", "the_long_horizon_plan", "claudius"]) },
  googlitch: { company: "Googlitch", name: "Googlitch — Ramp/Value",
    cards: dup(["pod_provisioner", "spin_up_tpu", "index_crawler", "search_index", "glitch_in_stack", "bardo_hallucinator", "tpu_megapod", "sunset_protocol", "gemma_twins", "gemini_ascendant"]) },
  shallowseek: { company: "ShallowSeek", name: "ShallowSeek — Swarm/Combo",
    cards: dup(["distil_bot_v3", "token_faucet", "quantize", "open_weights_intern", "fork_the_repo", "mixture_of_interns", "sparse_activation", "whale_class_cluster", "inference_cascade", "the_whale_open_sourced"]) },
};
